# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Scaleops < Formula
  desc "ScaleOps CLI."
  homepage "https://scaleops.sh/"
  version "0.0.5"
  license "Private"

  on_macos do
    url "https://github.com/scaleops-sh/scaleops-sh/releases/download/v0.0.5/scaleops_0.0.5_darwin_all.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "3836513f9de0076a097b89ff5b98031620a129f35356ffe5a8a68e07578a0f8d"

    def install
      bin.install "scaleops"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scaleops-sh/scaleops-sh/releases/download/v0.0.5/scaleops_0.0.5_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d514fdec6ead0ae3f501b880a028f4db3a1200565b0d72e3438a70d94251aa30"

      def install
        bin.install "scaleops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/scaleops-sh/scaleops-sh/releases/download/v0.0.5/scaleops_0.0.5_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ebbf5f74ff370c496c2b28bd9f1ae301e2fec96d53fd388bd1f6be9fc24f0021"

      def install
        bin.install "scaleops"
      end
    end
  end

  depends_on "helm"

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
