# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Scaleops < Formula
  desc "ScaleOps CLI."
  homepage "https://scaleops.sh/"
  version "0.0.2"
  license "Private"

  on_macos do
    url "https://github.com/scaleops-sh/scaleops-sh/releases/download/v0.0.2/scaleops_0.0.2_darwin_all.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "d8ce4b9147418e615544cb426f57a3c423dbe53f80558e1f292923621d1b679e"

    def install
      bin.install "scaleops"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scaleops-sh/scaleops-sh/releases/download/v0.0.2/scaleops_0.0.2_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "24a6604aaff4a258461ac37d8340ac9491dbbf2596e2a781e62218c254c0d612"

      def install
        bin.install "scaleops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/scaleops-sh/scaleops-sh/releases/download/v0.0.2/scaleops_0.0.2_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "30b6da5769f5bc260a8546c241fa176258764362a6fc1c91d99f4d8b0dd73837"

      def install
        bin.install "scaleops"
      end
    end
  end

  depends_on "helm"

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
