---
{{- if .Values.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
rules:
  - apiGroups:
      - ''
    resources:
      - limitranges
      - namespaces
      - pods
      - replicationcontrollers
      - replicationcontrollers/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - replicationcontrollers
      - statefulsets
      - daemonsets
      - deployments/scale
      - replicasets/scale
      - replicationcontrollers/scale
      - statefulsets/scale
      - daemonsets/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - deployments
      - replicasets
      - replicationcontrollers
      - statefulsets
      - daemonsets
      - deployments/scale
      - replicasets/scale
      - replicationcontrollers/scale
      - statefulsets/scale
      - daemonsets/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
      - cronjobs/scale
      - jobs/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - 'analysis.crane.io'
    resources:
      - recommendations
      - analytics
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - create
      - list
      - watch
      - update
      - patch

{{- end}}