---
{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.configMapName }}
data:
  config.yaml: {{- .Values.config.value | toYaml | indent 2 -}}
{{- end }}